# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.insurance.com:
  peer0.apple.insurance.com:
  peer0.billy.insurance.com:
  peer0.platform.insurance.com:
  peer0.medical.insurance.com:
  peer0.transport.insurance.com:

networks:
  byfn:

services:

  orderer.insurance.com:
    extends:
      file:   docker-compose-base-insurance.yaml
      service: orderer.insurance.com
    container_name: orderer.insurance.com
    environment:
      - GODEBUG=netdns=go
    networks:
      - byfn

  peer0.apple.insurance.com:
    container_name: peer0.apple.insurance.com
    extends:
      file:  docker-compose-base-insurance.yaml
      service: peer0.apple.insurance.com
    environment:
      - GODEBUG=netdns=go
    networks:
      - byfn

  peer0.billy.insurance.com:
    container_name: peer0.billy.insurance.com
    extends:
      file:  docker-compose-base-insurance.yaml
      service: peer0.billy.insurance.com
    environment:
      - GODEBUG=netdns=go
    networks:
      - byfn

  peer0.platform.insurance.com:
    container_name: peer0.platform.insurance.com
    extends:
      file:  docker-compose-base-insurance.yaml
      service: peer0.platform.insurance.com
    environment:
      - GODEBUG=netdns=go
    networks:
      - byfn

  peer0.medical.insurance.com:
    container_name: peer0.medical.insurance.com
    extends:
      file:  docker-compose-base-insurance.yaml
      service: peer0.medical.insurance.com
    environment:
      - GODEBUG=netdns=go
    networks:
      - byfn

  peer0.transport.insurance.com:
    container_name: peer0.transport.insurance.com
    extends:
      file:  base/docker-compose-base-insurance.yaml
      service: peer0.transport.insurance.com
    environment:
      - GODEBUG=netdns=go
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GODEBUG=netdns=go
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.apple.insurance.com:7051
      - CORE_PEER_LOCALMSPID=AppleMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.insurance.com/peers/peer0.apple.insurance.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.insurance.com/peers/peer0.apple.insurance.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.insurance.com/peers/peer0.apple.insurance.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/apple.insurance.com/users/Admin@apple.insurance.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.insurance.com
      - peer0.apple.insurance.com
      - peer0.billy.insurance.com
      - peer0.platform.insurance.com
      - peer0.medical.insurance.com
      - peer0.transport.insurance.com
    networks:
      - byfn
